In [1]:
import pandas as pd

In [2]:
csv_data = pd.read_csv('hbcsv.csv')

In [3]:
csv_data.columns

Index(['Brand', 'Name', 'Anchal', 'Type', 'Condition', 'Used For', 'Lot No',
       'Price', 'Mileage', 'Engine', 'Make Year', 'Kilometers'],
      dtype='object')

In [4]:
csv_data.rename(columns={'Lot No':  'Lot', 'Make Year': 'Make'})

,Brand,Name,Anchal,Type,Condition,Used For,Lot,Price,Mileage,Engine,Make,Kilometers
0,bajaj,pulsar,Bagmati,Sports,Excellent,NaN,53,1350000,40,200,2012,30k
1,bajaj,pulsar,Koshi,Sports,NaN,18months,27,220,50,NaN,2016,10000
2,bajaj,pulsar,Bagmati,Standard,Good/Fair,5 years,55,125000,38,150,2013,49000
3,enfield,classic,Bagmati,Standard,Excellent,few time,83,375000,NaN,350,NaN,9800
4,bajaj,avenger,Bagmati,Cruiser,Excellent,2.5 years,70,170000,30,220,2015,25500
5,bajaj,pulsar,Bagmati,Sports,Excellent,NaN,46,99999,40,150,NaN,NaN
6,UnKnown,UnKnown,Bagmati,Standard,Excellent,NaN,73,300000,37,350,2016,14000
7,yamaha,fz,Bagmati,Sports,Like New (used few times),12 month,93,230000,40,150,2017,2192
8,suzuki,gixxer,Bagmati,Sports,Excellent,2 years,73,160000,35,155,2015,35000
9,bajaj,pulsar,Bagmati,Standard,Good/Fair,8 years,36,80000,30,180,2009,70000
10,mahindra,rodeo,Bagmati,Scooty,Excellent,7 yrs,49,65000,30,125,2011,35000
11,honda,cbr,Bagmati,Sports,Excellent,NaN,48,180000,NaN,250,NaN,NaN
12,hartford,vr,Bagmati,Dirt,Excellent,NaN,38,135000,NaN,150,NaN,NaN
13,honda,dio,Bagmati,Scooty,Excellent,NaN,55,82000,40,108,2012,19000
14,yamaha,fz,Bagmati,Standard,Excellent,NaN,46,85000,35,150,2011,41500
15,hero,cbz,Bagmati,Standard,Like New (used few times),7years,50,95000,40,150,12,44000
16,yamaha,UnKnown,Bagmati,Sports,Excellent,NaN,52,125000,40,150,2012,40000
17,honda,shine,Bagmati,Standard,Like New (used few times),NaN,38,60000,NaN,NaN,2009,NaN
18,honda,dio,Bagmati,Scooty,Excellent,7 months,93,175000,35,110,2018,9k
19,yamaha,r15,Bagmati,Sports,Excellent,NaN,49,129000,30,150,NaN,NaN
20,UnKnown,UnKnown,Bagmati,Standard,Good/Fair,3yrs,62,130000,45,160,2015,40 abo
21,ktm,duke,Bagmati,Sports,Like New (used few times),2 years,77,360000,25,390,2016,15000
22,um,UnKnown,Bagmati,Cruiser,Like New (used few times),1 month,96,257000,35,NaN,NaN,900
23,UnKnown,UnKnown,Bagmati,Standard,Like New (used few times),9 month,89,305000,40,250,2017,7500
24,bajaj,ns,Bagmati,Standard,Good/Fair,4 month,52,135000,35,200,2069,20000
25,bajaj,UnKnown,Bagmati,Standard,Excellent,1yrs,80,139000,45,150,2017,11000
26,UnKnown,UnKnown,Bagmati,Sports,Excellent,NaN,32,65000,35,153,2008,NaN
27,honda,dio,Bagmati,Scooty,Excellent,1year,74,120000,40,100,NaN,16k +
28,tvs,jupiter,Bagmati,Scooty,Excellent,NaN,71,108000,33,110,2015,14000
29,ktm,UnKnown,Bagmati,Sports,Excellent,NaN,75,368000,30,200,2016,6900
...,...,...,...,...,...,...,...,...,...,...,...,...
3436,suzuki,UnKnown,Bheri,Dirt,Excellent,NaN,35,288000,48,125,2009,8950
3437,yamaha,UnKnown,Bagmati,Cruiser,Excellent,NaN,7,235000,30,250,1997,na
3438,ktm,duke,Bagmati,Standard,Excellent,NaN,51,290000,NaN,200,NaN,20000
3439,bajaj,avenger,Bagmati,Cruiser,Excellent,NaN,33,90000,35,200,NaN,NaN
3440,honda,UnKnown,Bagmati,Dirt,Excellent,NaN,8,325000,38,185,1999,na
3441,honda,xr,Bagmati,Dirt,Excellent,NaN,24,500000,35,200,1998,na
3442,honda,xr,Bagmati,Dirt,Excellent,NaN,23,465000,32,200,1999,na
3443,bajaj,pulsar,Bagmati,Sports,Like New (used few times),1 month,89,291000,34,200,2017,3000
3444,yamaha,UnKnown,Bagmati,Sports,Excellent,NaN,39,75000,45,125,2010,34500
3445,yamaha,UnKnown,Bagmati,Dirt,Good/Fair,15 yrs,8,475000,25,196,1999,xx
3446,yamaha,UnKnown,Janakpur,Standard,Like New (used few times),8 manth,9,180000,45,150,2017,5500
3447,tvs,apache,Bagmati,Sports,Like New (used few times),2 years,73,199000,NaN,180,2015,6000
3448,hero,splendor,Koshi,Standard,Excellent,3 years,21,116000,60,125,2015,22000+
3449,yamaha,r15,Bagmati,Sports,Like New (used few times),4 month,83,315000,35,150,2017,3000
3450,hero,UnKnown,Koshi,Standard,Like New (used few times),15 month,6,80000,NaN,NaN,NaN,NaN
3451,honda,hornet,Bagmati,Standard,Like New (used few times),1year,83,215000,45,160,2017,6000
3452,honda,hornet,Bagmati,Sports,Like New (used few times),1.5yrs,74,214999,35,160,2016,9900
3453,crossfire,UnKnown,Koshi,Dirt,Like New (used few times),NaN,28,480000,NaN,250,NaN,3300
3454,honda,dio,Bagmati,Scooty,Excellent,3 years,47,80000,35,102,2014,53000
3455,honda,dio,Bagmati,Scooty,NaN,NaN,62,109000,NaN,NaN,NaN,NaN
3456,honda,unicorn,Bagmati,Standard,Excellent,3years,47,135500,60,150,2015,21000
3457,ktm,UnKnown,Bagmati,Standard,Excellent,2year,73,310000,25,199.50,2016,"16,000"
3458,enfield,UnKnown,Bagmati,Standard,Excellent,NaN,15,300000,NaN,500,2005,NaN
3459,yamaha,UnKnown,Bagmati,Standard,Excellent,NaN,4,45000,30,100,NaN,29000
3460,honda,unicorn,Bagmati,Standard,Excellent,8 years,23,80000,40,150,200,24000
3461,vespa,UnKnown,Bagmati,Scooty,Like New (used few times),NaN,11,110000,NaN,150,NaN,NaN
3462,um,UnKnown,Bagmati,Sports,Excellent,3 years,62,130000,30,230,2014,36000
3463,ducati,UnKnown,Bagmati,Sports,Excellent,NaN,55,2800000,NaN,1200,2012,6000
3464,hero,splendor,Bagmati,Standard,Good/Fair,NaN,7,50000,40,100,NaN,NaN
3465,mahindra,rodeo,Bagmati,Scooty,Good/Fair,3years,49,65000,30,125,2012,7000